/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ttN0-dev/t/Dercel (Based on your new design)
 * Includes fixed percentage logic
 */
import { Progress } from "@/components/ui/progress"
import { CalendarIcon, DumbbellIcon, DropletIcon, HeartIcon } from "lucide-react"

export default function TrackerApp() {
  // --- FIXED LOGIC ---
  // Define placeholder variables for the current status and goals 
  // We use reasonable numbers (75, 85, etc.) instead of the v0-generated errors.
  const waterProgress = 75 
  const nutritionProgress = 85
  const exerciseProgress = 60
  const sleepProgress = 90
  // --- END FIXED LOGIC ---

  return (
    <div className="flex flex-col min-h-screen bg-[#0d1117] text-gray-200">
      <header className="py-4 px-6 border-b border-gray-700">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold">100 Year Health Tracker</h1>
          <div className="flex items-center space-x-2">
            <CalendarIcon className="w-5 h-5" />
            <DumbbellIcon className="w-5 h-5" />
          </div>
        </div>
      </header>
      <main className="flex-1 p-6">
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-4 text-green-400 border-b border-green-400 pb-1">Today's Progress</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            <ProgressCard
              title="Water Intake"
              icon={DropletIcon}
              progress={waterProgress}
              goal={`Goal: 8 glasses`}
              className="bg-[#161b22]"
              color="text-blue-400"
            />
            <ProgressCard
              title="Nutrition"
              icon={HeartIcon}
              progress={nutritionProgress}
              goal="Goal: 5 portions of fruits/veg"
              className="bg-[#161b22]"
              color="text-pink-400"
            />
            <ProgressCard
              title="Exercise"
              icon={DumbbellIcon}
              progress={exerciseProgress}
              goal="Goal: 30 minutes active"
              className="bg-[#161b22]"
              color="text-green-400"
            />
            <ProgressCard
              title="Sleep Quality"
              icon={CalendarIcon}
              progress={sleepProgress}
              goal="Goal: 7-9 hours"
              className="bg-[#161b22]"
              color="text-cyan-400"
            />
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-4 text-green-400 border-b border-green-400 pb-1">Monthly Overview (Workout Planner)</h2>
          <div className="bg-[#161b22] p-6 rounded-lg shadow-xl">
            <p className="text-gray-400">
              *Your custom calendar for Barbell and Bench workouts will be built here.*
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}

function ProgressCard({ title, icon: Icon, progress, goal, className, color }) {
  return (
    <div className={`p-6 rounded-xl shadow-2xl ${className} border border-[#21262d]`}>
      <div className="flex justify-between items-center mb-3">
        <h3 className="text-lg font-semibold">{title}</h3>
        <Icon className={`w-6 h-6 ${color}`} />
      </div>
      <div className="text-4xl font-extrabold mb-3">{progress}%</div>
      <Progress value={progress} className="h-2 bg-gray-700" indicatorClassName={`bg-current ${color.replace('text-', 'bg-')}`} />
      <p className="text-sm text-gray-400 mt-3">{goal}</p>
    </div>
  )
}
